debug: false
experimentName: example_FashionMNIST-network-morphism
maxExperimentDuration: 48h
maxTrialNumber: 200
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 FashionMNIST_keras.py
trialConcurrency: 4
trialGpuNumber: 1
tuner:
  classArgs: {input_channel: 1, input_width: 28, n_output_node: 10, optimize_mode: maximize,
    task: cv}
  name: NetworkMorphism
useAnnotation: false
