debug: false
experimentName: example_FashionMNIST-network-morphism
maxExperimentDuration: 24h
maxTrialNumber: 10
trainingService:
  containerStorageMountPoint: {replace_to_your_container_mount_path: null}
  dockerImage: msranni/nni:latest
  host: 10.10.10.10
  localStorageMountPoint: {replace_to_your_nfs_mount_path: null}
  platform: openpai
  reuseMode: false
  storageConfigName: {replace_to_your_storage_config_name: null}
  token: token
  trialCpuNumber: 1
  trialMemorySize: 8196
  username: username
trialCodeDirectory: .
trialCommand: python3 FashionMNIST_keras.py
trialConcurrency: 1
trialGpuNumber: 1
tuner:
  classArgs: {input_channel: 1, input_width: 28, n_output_node: 10, optimize_mode: maximize,
    task: cv}
  name: NetworkMorphism
useAnnotation: false
