debug: false
experimentName: example_tgs
maxExperimentDuration: 10h
maxTrialNumber: 10
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 train.py
trialConcurrency: 2
trialGpuNumber: 1
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: true
