debug: false
experimentName: example_pytorch_cifar10
maxExperimentDuration: 100h
maxTrialNumber: 10
searchSpaceFile: search_space.json
trainingService: {maxTrialNumberPerGpu: 2, platform: local}
trialCodeDirectory: .
trialCommand: python3 main.py
trialConcurrency: 4
trialGpuNumber: 1
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: false
