debug: false
experimentName: example_cifar10-network-morphism
maxExperimentDuration: 48h
maxTrialNumber: 200
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 cifar10_keras.py
trialConcurrency: 4
trialGpuNumber: 1
tuner:
  classArgs: {input_channel: 3, input_width: 32, n_output_node: 10, optimize_mode: maximize,
    task: cv}
  name: NetworkMorphism
useAnnotation: false
