debug: false
experimentName: example_mnist_pytorch
maxExperimentDuration: 1h
maxTrialNumber: 10
searchSpaceFile: search_space.json
trainingService: {computeTarget: '${replace_to_your_computeTarget}', dockerImage: msranni/nni,
  platform: aml, resourceGroup: '${replace_to_your_resourceGroup}', subscriptionId: '${replace_to_your_subscriptionId}',
  workspaceName: '${replace_to_your_workspaceName}'}
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 1
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: false
