advisor:
  classArgs: {k: 3}
  classDirectory: !!python/object/apply:pathlib.PosixPath []
  className: dummy_advisor.DummyAdvisor
debug: false
experimentName: example_customized_advisor
maxExperimentDuration: 1h
maxTrialNumber: 200
searchSpaceFile: search_space.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 mnist_keras.py --epochs 100 --num_train 600 --num_test 100
trialConcurrency: 4
trialGpuNumber: 0
useAnnotation: false
