advisor:
  classArgs: {eta: 3, max_budget: 27, min_budget: 1, optimize_mode: maximize}
  name: BOHB
debug: false
experimentName: example_mnist_bohb
maxExperimentDuration: 10h
maxTrialNumber: 1000
searchSpaceFile: search_space.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 1
trialGpuNumber: 0
useAnnotation: false
