advisor:
  classArgs: {R: 100, eta: 3, exec_mode: parallelism, optimize_mode: maximize}
  name: Hyperband
debug: false
experimentName: example_mnist_hyperband
maxExperimentDuration: 1h
maxTrialNumber: 10000
searchSpaceFile: search_space.json
trainingService: {containerStorageMountPoint: /mnt/data/user, dockerImage: msranni/nni:latest,
  host: 10.10.10.10, localStorageMountPoint: /home/user/mnt, platform: openpai, reuseMode: false,
  storageConfigName: confignfs-data, token: token, trialCpuNumber: 1, trialMemorySize: 8196,
  username: username}
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 10
trialGpuNumber: 0
useAnnotation: false
