debug: false
experimentName: example_dist
maxExperimentDuration: 1h
maxTrialNumber: 1
trainingService:
  apiVersion: v1alpha2
  operator: tf-operator
  platform: kubeflow
  storage: {path: /var/nfs/general, server: 10.10.10.10, storage: nfs}
  worker:
    command: python3 mnist.py
    cpuNumber: !!python/object:dataclasses._MISSING_TYPE {}
    dockerImage: msranni/nni:latest
    gpuNumber: !!python/object:dataclasses._MISSING_TYPE {}
    memorySize: 8192
    replicas: 1
trialCodeDirectory: .
trialCommand: !!python/object:dataclasses._MISSING_TYPE {}
trialConcurrency: 1
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: true
