debug: false
experimentName: example_mnist
maxExperimentDuration: 1h
maxTrialNumber: 10
trainingService:
  machineList:
  - {host: 10.1.1.1, maxTrialNumberPerGpu: 1, password: bob123, port: 22, useActiveGpu: false,
    user: bob}
  - {host: 10.1.1.2, maxTrialNumberPerGpu: 1, password: bob123, port: 22, useActiveGpu: false,
    user: bob}
  - {host: 10.1.1.3, maxTrialNumberPerGpu: 1, password: bob123, port: 22, useActiveGpu: false,
    user: bob}
  platform: remote
  reuseMode: false
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 1
trialGpuNumber: 0
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: true
