debug: false
experimentName: example_mnist
maxExperimentDuration: 1h
maxTrialNumber: 10
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 4
trialGpuNumber: 1
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: true
