debug: false
experimentName: example_mnist
maxExperimentDuration: 1h
maxTrialNumber: 10
searchSpaceFile: search_space.json
trainingService:
  machineList:
  - {host: '${replace_to_your_remote_machine_ip}', maxTrialNumberPerGpu: 1, port: 22,
    sshKeyFile: '${replace_to_your_remote_machine_sshKeyPath}', trialPrepareCommand: 'export
      PATH=${replace_to_python_environment_path_in_your_remote_machine}:$PATH', useActiveGpu: false,
    user: '${replace_to_your_remote_machine_username}'}
  platform: remote
  reuseMode: false
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 1
trialGpuNumber: 0
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: false
