debug: false
experimentName: example_efficient_net
maxExperimentDuration: 99999d
maxTrialNumber: 100
searchSpaceFile: search_net.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: EfficientNet-PyTorch
trialCommand: python main.py /data/imagenet -j 12 -a efficientnet --batch-size 48
  --lr 0.048 --wd 1e-5 --epochs 5 --request-from-nni
trialConcurrency: 4
trialGpuNumber: 1
tuner:
  classArgs: {product: 2}
  classDirectory: !!python/object/apply:pathlib.PosixPath []
  className: tuner.FixedProductTuner
useAnnotation: false
