debug: false
experimentName: example_mnist_pbt_tuner_pytorch
maxExperimentDuration: 2h
maxTrialNumber: 100
searchSpaceFile: search_space.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 3
trialGpuNumber: 1
tuner:
  classArgs: {optimize_mode: maximize}
  name: PBTTuner
useAnnotation: false
