debug: false
experimentName: example_mnist-keras
maxExperimentDuration: 1h
maxTrialNumber: 10
searchSpaceFile: search_space.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 mnist-keras.py
trialConcurrency: 1
trialGpuNumber: 0
tuner: {name: BatchTuner}
useAnnotation: false
