debug: false
experimentName: mnist-nested-search-space
maxExperimentDuration: 1h
maxTrialNumber: 100
searchSpaceFile: search_space.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 2
trialGpuNumber: 0
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: false
