debug: false
experimentName: ga_squad_weight_sharing
maxExperimentDuration: 1h
maxTrialNumber: 200
trainingService:
  machineList:
  - {host: remote-ip-0, maxTrialNumberPerGpu: 1, password: screencast, port: 8022,
    useActiveGpu: false, user: root}
  - {host: remote-ip-1, maxTrialNumberPerGpu: 1, password: screencast, port: 8022,
    useActiveGpu: false, user: root}
  platform: remote
  reuseMode: false
trialCodeDirectory: .
trialCommand: python3 trial.py --input_file /mnt/nfs/nni/train-v1.1.json --dev_file
  /mnt/nfs/nni/dev-v1.1.json --max_epoch 1 --embedding_file /mnt/nfs/nni/glove.6B.300d.txt
trialConcurrency: 2
trialGpuNumber: 1
tuner:
  classArgs: {optimize_mode: maximize, population_size: 32, save_dir_root: /mnt/nfs/nni/ga_squad}
  classDirectory: !!python/object/apply:pathlib.PosixPath [.., .., .., tuners, weight_sharing,
    ga_customer_tuner]
  className: customer_tuner.CustomerTuner
useAnnotation: false
