debug: false
experimentName: example_sklearn-regression
maxExperimentDuration: 1h
maxTrialNumber: 30
searchSpaceFile: search_space.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 main.py
trialConcurrency: 1
trialGpuNumber: 0
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: false
