advisor:
  classArgs: {R: 60, eta: 3, exec_mode: serial, optimize_mode: maximize}
  name: Hyperband
debug: false
experimentName: example_mnist_hyperband
maxExperimentDuration: 100h
maxTrialNumber: 10000
searchSpaceFile: search_space.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 main.py
trialConcurrency: 2
trialGpuNumber: 0
useAnnotation: false
