debug: false
experimentName: example_ga_squad
maxExperimentDuration: 1h
maxTrialNumber: 10
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 trial.py
trialConcurrency: 1
trialGpuNumber: 0
tuner:
  classArgs: {optimize_mode: maximize}
  classDirectory: !!python/object/apply:pathlib.PosixPath [.., .., tuners, ga_customer_tuner]
  className: customer_tuner.CustomerTuner
useAnnotation: false
