debug: false
experimentName: example_ga_squad
maxExperimentDuration: 1h
maxTrialNumber: 10
nniManagerIp: 10.10.10.10
trainingService: {containerStorageMountPoint: /mnt/data/user, dockerImage: msranni/nni:latest,
  host: 10.10.10.10, localStorageMountPoint: /home/user/mnt, platform: openpai, reuseMode: false,
  storageConfigName: confignfs-data, token: token, trialCpuNumber: 1, trialMemorySize: 32869,
  username: username}
trialCodeDirectory: .
trialCommand: chmod +x ./download.sh && ./download.sh && python3 trial.py
trialConcurrency: 1
trialGpuNumber: 0
tuner:
  classArgs: {optimize_mode: maximize}
  classDirectory: !!python/object/apply:pathlib.PosixPath [.., .., tuners, ga_customer_tuner]
  className: customer_tuner.CustomerTuner
useAnnotation: false
