debug: false
experimentName: example_mnist
maxExperimentDuration: 1h
maxTrialNumber: 10
searchSpaceFile: search_space.json
trainingService:
  containerStorageMountPoint: {replace_to_your_container_mount_path: null}
  dockerImage: msranni/nni:latest
  host: 10.10.10.10
  localStorageMountPoint: {replace_to_your_nfs_mount_path: null}
  platform: openpai
  reuseMode: false
  storageConfigName: {replace_to_your_storage_config_name: null}
  token: token
  trialCpuNumber: 1
  trialMemorySize: 8196
  username: username
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 1
trialGpuNumber: 0
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: false
