assessor:
  classArgs: {optimize_mode: maximize}
  name: Medianstop
debug: false
experimentName: example_mnist
maxExperimentDuration: 1h
maxTrialNumber: 20
searchSpaceFile: search_space.json
trainingService:
  apiVersion: v1alpha2
  operator: tf-operator
  parameterServer:
    command: python3 dist_mnist.py
    cpuNumber: !!python/object:dataclasses._MISSING_TYPE {}
    dockerImage: msranni/nni:latest
    gpuNumber: !!python/object:dataclasses._MISSING_TYPE {}
    memorySize: 8196
    replicas: 1
  platform: kubeflow
  storage:
    path: {your_nfs_server_export_path: null}
    server: {your_nfs_server_ip: null}
    storage: nfs
  worker:
    command: python3 dist_mnist.py
    cpuNumber: !!python/object:dataclasses._MISSING_TYPE {}
    dockerImage: msranni/nni:latest
    gpuNumber: !!python/object:dataclasses._MISSING_TYPE {}
    memorySize: 8196
    replicas: 2
trialCodeDirectory: .
trialCommand: !!python/object:dataclasses._MISSING_TYPE {}
trialConcurrency: 2
tuner:
  classArgs: {optimize_mode: maximize}
  name: TPE
useAnnotation: false
