debug: false
experimentName: example_auto-gbdt-metis
maxExperimentDuration: 10h
maxTrialNumber: 10
searchSpaceFile: search_space_metis.json
trainingService: {maxTrialNumberPerGpu: 1, platform: local}
trialCodeDirectory: .
trialCommand: python3 main.py
trialConcurrency: 1
trialGpuNumber: 0
tuner:
  classArgs: {optimize_mode: minimize}
  name: MetisTuner
useAnnotation: false
